### ISSUE TITLE
Develop a swagger document based on the existing documentation

### ISSUE THREAD

**Issue by kshychko** [ausdigital/ausdigital-tap-gw#2]
https://tap-gw.testpoint.io/api/docs/

**Comment by koriaf** [comment]
please don't forget to link tap-gw.testpoint.io to new document location, and delete old one to avoid ambiguity.

**Comment by monkeypants** [comment]
We seem to have problems with doc generation here. Published pages don't seem to reflect the latest swagger spec.

**Comment by monkeypants** [comment]
can we close this ticket @kshychko ? it's looking fairly done to me.

**Comment by kshychko** [comment]
I have updated tap-gw.testpoint.io and deleted the documentation in RTD format finally.
Now the issue can be closed.
